[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "robox-sdk-lite"
version = "1.0.2"
authors = [
  { name="Paco Li Junting", email="paco.li@intedigo.com" },
]
description = "Robox SDK Lite for Intedigo RoIO Robot System"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]
dependencies = [
]

[project.urls]
"Homepage" = "https://github.com/PacoLijt/robox-sdk-lite"
"Bug Tracker" = "https://github.com/PacoLijt/robox-sdk-lite/issues"

[tool.hatch.build.targets.wheel]
packages = ["src/robox-sdk-lite"]
